# Generated by Django 4.2.7 on 2026-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_general",
                    models.EmailField(default="info@bclproduction.com", max_length=254),
                ),
                (
                    "email_booking",
                    models.EmailField(
                        default="booking@bclproduction.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(default="+254 799 804 185", max_length=20)),
                ("address", models.TextField(default="Nairobi, Kenya\n00100 Ngara")),
                ("instagram", models.URLField(blank=True, null=True)),
                ("tiktok", models.URLField(blank=True, null=True)),
                ("youtube", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                (
                    "business_hours",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("auto_reply_enabled", models.BooleanField(default=True)),
                (
                    "auto_reply_subject",
                    models.CharField(
                        default="Thank you for contacting BCL PRODUCTION",
                        max_length=200,
                    ),
                ),
                (
                    "auto_reply_message",
                    models.TextField(
                        default="Thank you for reaching out to BCL PRODUCTION. We have received your message and will get back to you within 24-48 business hours.\n\nBest regards,\nBCL PRODUCTION Team"
                    ),
                ),
                (
                    "google_maps_api_key",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "map_latitude",
                    models.DecimalField(
                        decimal_places=7, default=-1.286389, max_digits=10
                    ),
                ),
                (
                    "map_longitude",
                    models.DecimalField(
                        decimal_places=7, default=36.817223, max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Settings",
                "verbose_name_plural": "Contact Settings",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("booking", "Booking Request"),
                            ("collaboration", "Collaboration"),
                            ("workshop", "Workshop Inquiry"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "subject_other",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Custom Subject",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="BCL_contact_email_4cced0_idx"),
                    models.Index(
                        fields=["status"], name="BCL_contact_status_ddf4f1_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="BCL_contact_created_acd6ad_idx"
                    ),
                ],
            },
        ),
    ]
