# Generated by Django 4.2.7 on 2026-05-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BCL", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="About BCL PRODUCTION", max_length=200),
                ),
                (
                    "content",
                    models.TextField(
                        default="BCL PRODUCTION is a leading media production company based in Nairobi, Kenya..."
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="about_images/"),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Upload MP4, WebM, or MOV files",
                        null=True,
                        upload_to="about_videos/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Sections",
            },
        ),
    ]
