# Generated by Django 4.2.7 on 2026-05-07 15:48

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("industry", models.CharField(default="", max_length=200)),
                ("location", models.CharField(default="", max_length=200)),
                ("website", models.URLField(blank=True, default="", null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("email", models.EmailField(blank=True, default="", max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ratings",
                    models.CharField(
                        choices=[
                            ("ONE_STAR", "ONE_STAR"),
                            ("TWO_STAR", "TWO_STAR"),
                            ("THREE_STAR", "THREE_STAR"),
                            ("FOUR_STAR", "FOUR_STAR"),
                            ("FIVE_STAR", "FIVE_STAR"),
                        ],
                        default="THREE_STAR",
                        max_length=20,
                    ),
                ),
                ("teamwork", models.FloatField(default=0.0)),
                ("time_management", models.FloatField(default=0.0)),
                ("critical_thinking", models.FloatField(default=0.0)),
                ("leadership", models.FloatField(default=0.0)),
                ("Communication", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="SeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pfp",
                    models.ImageField(
                        default="SeekerPfp/default.jpg", upload_to="SeekerPfp"
                    ),
                ),
                (
                    "primary_trade",
                    models.CharField(
                        choices=[
                            ("electrician", "Electrician"),
                            ("welder", "Welder"),
                            ("plumber", "Plumber"),
                            ("carpenter", "Carpenter"),
                            ("hvac", "HVAC Technician"),
                            ("operator", "Heavy Equipment Operator"),
                            ("mechanic", "Mechanic"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "years_experience",
                    models.CharField(
                        choices=[
                            ("0-2", "Entry Level (0-2 years)"),
                            ("3-5", "Mid Level (3-5 years)"),
                            ("5-10", "Senior Level (5-10 years)"),
                            ("10+", "Expert Level (10+ years)"),
                        ],
                        max_length=5,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("seeking", "Seeking"),
                            ("employed", "Employed"),
                            ("freelancing", "Freelancing"),
                            ("idle", "Idle"),
                        ],
                        default="seeking",
                        max_length=20,
                    ),
                ),
                (
                    "profile_completion",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                ("contact", models.CharField(default="+2547", max_length=13)),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Seeker", "Seeker / Job Seeker"),
                            ("Employer", "Employer / Recruiter"),
                            ("Developer", "Developer / Admin"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "agree_terms",
                    models.BooleanField(default=False, verbose_name="Agreed to Terms"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="", max_length=100)),
                ("position", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(default=False)),
                ("my_description", models.CharField(default="", max_length=300)),
                ("employer_description", models.CharField(default="", max_length=300)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thecompany",
                        to="Users.company",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experience",
                        to="Users.seekerprofile",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workExperience",
                        to="Users.review",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="seekerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seeker_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="Users.seekerprofile",
            ),
        ),
        migrations.CreateModel(
            name="DmFromResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        default="Checking Availabilty To Hire", max_length=100
                    ),
                ),
                ("location", models.TextField(default="")),
                ("hourly_rate", models.FloatField(default=10.0)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            {"Online", "online"},
                            {"Offline", "offline"},
                            {"Hybrid", "hybrid"},
                            {"Contract", "contract"},
                        ],
                        default="hybrid",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(default="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="Users.company",
                    ),
                ),
                (
                    "talent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="Users.seekerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField(default="")),
                ("rating", models.IntegerField(default=0)),
                (
                    "company_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.companyreview",
            ),
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="Users.seekerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolProficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=100)),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=15,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="Users.seekerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "tool_name")},
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="Users.seekerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "name")},
            },
        ),
        migrations.CreateModel(
            name="SeekerSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=15,
                    ),
                ),
                ("years_experience", models.IntegerField(default=1)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="Users.seekerprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.skill"
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "skill")},
            },
        ),
    ]
