# Generated by Django 4.2.7 on 2026-05-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seekerprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="seekerprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
