# Generated by Django 4.2.7 on 2026-05-09 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_seekerprofile_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dmfromresume",
            name="company",
        ),
        migrations.AddField(
            model_name="dmfromresume",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
