# Generated by Django 4.2.7 on 2026-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_remove_dmfromresume_company_dmfromresume_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dmfromresume",
            name="sender",
        ),
        migrations.AddField(
            model_name="dmfromresume",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="dmfromresume",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
