# Generated by Django 4.2.7 on 2026-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_remove_dmfromresume_sender_dmfromresume_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dmfromresume",
            name="hourly_rate",
        ),
        migrations.AddField(
            model_name="dmfromresume",
            name="contact",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="dmfromresume",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="dmfromresume",
            name="link",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
