# Generated by Django 4.2.7 on 2026-05-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_remove_dmfromresume_hourly_rate_dmfromresume_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Seeker", "Seeker / Job Seeker"),
                    ("Student", "Student / Apprentice"),
                    ("Institution", "Institution / Training Provider"),
                    ("Company", "Employer / Recruiter"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Type",
            ),
        ),
    ]
