# Generated by Django 4.2.7 on 2026-05-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0007_employerprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployerProfile",
        ),
    ]
