# Generated by Django 4.2.7 on 2026-05-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0008_delete_employerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="year_founded",
            field=models.IntegerField(blank=True, default=2020, null=True),
        ),
    ]
