# Generated by Django 4.2.7 on 2026-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0009_company_year_founded"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="pfp",
            field=models.ImageField(
                default="CompanyPfp/default.jpg", upload_to="CompanyPfp"
            ),
        ),
    ]
