# Generated by Django 4.2.7 on 2026-05-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0011_companyspecialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_specialization",
                to="Users.companyspecialization",
            ),
        ),
    ]
