# Generated by Django 4.2.7 on 2026-05-09 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0012_company_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyreview",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
