# Generated by Django 4.2.7 on 2026-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0013_companyreview_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyreview",
            name="company_name",
        ),
        migrations.AddField(
            model_name="companyreview",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="companyreview",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
