# Generated by Django 4.2.7 on 2026-05-09 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0014_remove_companyreview_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyreview",
            name="company_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="Users.company",
            ),
        ),
    ]
