# Generated by Django 4.2.7 on 2026-05-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0015_companyreview_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyreview",
            name="service",
            field=models.TextField(
                default="offerd software solution to relate with customers"
            ),
        ),
    ]
