# Generated by Django 4.2.7 on 2026-05-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0016_companyreview_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="DmFromCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(default="", max_length=255)),
                (
                    "subject",
                    models.CharField(
                        default="Checking Availabilty To Hire", max_length=100
                    ),
                ),
                ("contact", models.CharField(default="", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("description", models.TextField(default="")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="Users.company",
                    ),
                ),
            ],
        ),
    ]
