# Generated by Django 6.0.1 on 2026-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website_or_social', models.URLField(blank=True, help_text='Website, YouTube, Instagram, TikTok, etc.')),
                ('audience_size', models.CharField(blank=True, choices=[('under_1k', 'Under 1,000'), ('1k_10k', '1,000 - 10,000'), ('10k_50k', '10,000 - 50,000'), ('50k_plus', '50,000+')], max_length=20)),
                ('promotion_channels', models.CharField(blank=True, help_text='Comma-separated, e.g. Blog, YouTube, Instagram, Email list', max_length=300)),
                ('strategy', models.TextField(blank=True, help_text='How they plan to promote BlackCodeLabs')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Affiliate Application',
                'verbose_name_plural': 'Affiliate Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
