# Generated by Django 6.0.1 on 2026-08-21 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_reseed_blackcodelabs_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-published_at'], name='Blogs_post_status_2e89b6_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'featured'], name='Blogs_post_status_5eb302_idx'),
        ),
    ]
