# Generated by Django 6.0.1 on 2026-09-05 17:47

import utils.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_post_blogs_post_status_2e89b6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', validators=[utils.upload_validators.validate_image_10mb]),
        ),
    ]
