# Generated by Django 5.2.7 on 2026-04-29 21:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Application'), ('desktop', 'Desktop Application'), ('ai', 'Artificial Intelligence'), ('iot', 'IoT & Hardware'), ('data', 'Data Science'), ('other', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('documentation_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('coding_price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, help_text='Leave blank for custom project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pitchs.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
