# Generated by Django 5.2.7 on 2026-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pitchs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='coding_price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='documentation_price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='project',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
