# Generated by Django 5.2.7 on 2026-02-10 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pitchs', '0002_remove_project_coding_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='coding_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='documentation_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Leave blank for custom project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pitchs.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Application'), ('desktop', 'Desktop Application'), ('ai', 'Artificial Intelligence'), ('iot', 'IoT & Hardware'), ('data', 'Data Science'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
