# Generated by Django 4.2.7 on 2026-02-25 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("SalesPro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("salary", models.IntegerField(default=0)),
                ("contact", models.CharField(default="+254", max_length=20)),
                ("role", models.CharField(default="Employee", max_length=50)),
                ("location", models.CharField(default="Nairobi", max_length=50)),
                (
                    "picture",
                    models.ImageField(
                        default="Employee/default.png", null=True, upload_to="Employee"
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("shop", "name", "contact")},
            },
        ),
    ]
