# Generated by Django 5.2.7 on 2026-01-28 07:29

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_position', models.CharField(max_length=100)),
                ('client_company', models.CharField(blank=True, max_length=100, null=True)),
                ('client_picture', models.ImageField(help_text='Upload a profile picture (recommended: 400x400 pixels)', upload_to='client_pictures/', validators=[Home.models.validate_image_size])),
                ('review_text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Review')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Reviews',
                'ordering': ['-is_featured', '-display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('projects_delivered', models.IntegerField(default=1000, verbose_name='Projects Delivered')),
                ('systems_automated', models.IntegerField(default=1000, verbose_name='Systems Automated')),
                ('happy_clients', models.IntegerField(default=0, verbose_name='Happy Clients')),
                ('returning_clients', models.IntegerField(default=1000, verbose_name='Returning Clients')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from website', verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Counter',
                'verbose_name_plural': 'Data Counters',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(help_text='Upload a square image (passport size: 2x2 inches or 600x600 pixels)', upload_to='team_pictures/', validators=[Home.models.validate_image_size])),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Higher number appears first')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechServices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('icon', models.TextField(verbose_name='Icon HTML')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tech Service',
                'verbose_name_plural': 'Tech Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
