# Generated by Django 5.2.7 on 2026-01-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techservices',
            options={'ordering': ['created_at'], 'verbose_name': 'Tech Service', 'verbose_name_plural': 'Tech Services'},
        ),
    ]
