# Generated by Django 4.2.7 on 2026-06-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamMember",
        ),
    ]
