# Generated by Django 6.0.1 on 2026-08-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App'), ('api', 'API / Backend'), ('ai', 'AI & Automation'), ('ecommerce', 'E-Commerce'), ('branding', 'Branding & Design'), ('other', 'Other')], default='web', max_length=20)),
                ('summary', models.CharField(help_text='Short summary shown on the grid card', max_length=280)),
                ('description', models.TextField(blank=True, help_text='Longer case-study copy')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated, e.g. Django, React Native, PostgreSQL', max_length=300)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('cover_image_url', models.URLField(blank=True, help_text='Optional fallback image if no file is uploaded')),
                ('project_url', models.URLField(blank=True, help_text='Live site / app store link')),
                ('completed_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['display_order', '-completed_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pricing FAQ',
                'verbose_name_plural': 'Pricing FAQs',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Starter, Premium, Enterprise', max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('tagline', models.CharField(help_text='One line describing who this plan is for', max_length=200)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank for a 'Let's Talk' / custom-quote plan", max_digits=10, null=True)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per month when billed annually. Leave blank to auto-calc at 20% off.', max_digits=10, null=True)),
                ('currency_symbol', models.CharField(default='$', max_length=4)),
                ('custom_price_label', models.CharField(blank=True, default='', help_text='Shown instead of a number, e.g. "Let\'s Talk" (for the Enterprise/custom plan)', max_length=40)),
                ('is_featured', models.BooleanField(default=False, help_text="Highlights this plan as 'Most Popular'")),
                ('featured_badge_text', models.CharField(default='Most Popular', max_length=40)),
                ('eyebrow_text', models.CharField(blank=True, default='', help_text="Small label above the plan name, e.g. 'Enterprise'", max_length=40)),
                ('cta_text', models.CharField(default='Get Started', max_length=60)),
                ('cta_url_name', models.CharField(blank=True, default='contact', help_text="A named URL to reverse (e.g. 'contact'). Falls back to cta_external_url if it can't be resolved.", max_length=100)),
                ('cta_external_url', models.CharField(blank=True, default='', max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_included', models.BooleanField(default=True, help_text='Unchecked shows a dimmed ✗ row')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Home.pricingplan')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
