# Generated by Django 4.2.7 on 2026-06-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_delete_teammember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinquiry",
            name="department",
        ),
    ]
