# Generated by Django 6.0.1 on 2026-08-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_seed_pricing_and_portfolio'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['is_active', 'category'], name='Home_portfo_is_acti_b01049_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['is_active', 'is_featured'], name='Home_portfo_is_acti_80e94a_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingplan',
            index=models.Index(fields=['is_active', 'display_order'], name='Home_pricin_is_acti_102649_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['is_active', 'display_order'], name='Home_soluti_is_acti_68d9ed_idx'),
        ),
    ]
