# Generated by Django 5.2.7 on 2026-01-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_contactinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
