# Generated by Django 5.2.7 on 2026-01-28 11:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_contactinquiry_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=100)),
                ('demo_date', models.DateField()),
                ('demo_time', models.CharField(choices=[('09:00', '9:00 AM'), ('09:30', '9:30 AM'), ('10:00', '10:00 AM'), ('10:30', '10:30 AM'), ('11:00', '11:00 AM'), ('11:30', '11:30 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('13:30', '1:30 PM'), ('14:00', '2:00 PM'), ('14:30', '2:30 PM'), ('15:00', '3:00 PM'), ('15:30', '3:30 PM'), ('16:00', '4:00 PM'), ('16:30', '4:30 PM'), ('17:00', '5:00 PM')], max_length=5)),
                ('demo_title', models.CharField(max_length=200)),
                ('service_type', models.CharField(blank=True, choices=[('automation', 'Process Automation'), ('ai', 'AI Solutions'), ('development', 'Custom Development'), ('data', 'Data Intelligence'), ('security', 'Security Solutions'), ('training', 'Technology Training'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=20, null=True)),
                ('demo_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('number_of_attendees', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('meeting_platform', models.CharField(choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('google', 'Google Meet'), ('other', 'Other')], default='Zoom', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_password', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_demos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Booking',
                'verbose_name_plural': 'Demo Bookings',
                'ordering': ['-demo_date', 'demo_time'],
                'indexes': [models.Index(fields=['demo_date', 'demo_time'], name='Home_demobo_demo_da_6dc0e7_idx'), models.Index(fields=['email'], name='Home_demobo_email_50d555_idx'), models.Index(fields=['status'], name='Home_demobo_status_c8cc53_idx')],
            },
        ),
    ]
