# Generated by Django 6.0.1 on 2026-09-02 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_seed_portfolio_project_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientreview',
            index=models.Index(fields=['-is_featured', '-display_order', '-created_at'], name='Home_client_is_feat_aa4573_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['-created_at'], name='Home_contac_created_f13326_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['status', '-created_at'], name='Home_contac_status_a590f7_idx'),
        ),
    ]
