# Generated by Django 5.2.7 on 2026-01-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_demobooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used in URLs and for identification', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=200)),
                ('detailed_description', models.TextField()),
                ('icon_class', models.CharField(choices=[('fa-code', 'Code'), ('fa-robot', 'Robot'), ('fa-database', 'Database'), ('fa-comments', 'Comments'), ('fa-shield-alt', 'Shield'), ('fa-server', 'Server'), ('fa-network-wired', 'Network'), ('fa-graduation-cap', 'Graduation Cap')], max_length=50)),
                ('z_index', models.IntegerField(default=0, help_text='CSS z-index value for styling')),
                ('features', models.TextField(help_text='Enter features separated by new lines. Each line will become a list item.')),
                ('cta_text', models.CharField(default='Learn More', max_length=50)),
                ('cta_link', models.CharField(default='#', max_length=200)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which solutions are displayed (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technology Solution',
                'verbose_name_plural': 'Technology Solutions',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
