# Generated by Django 6.0.1 on 2026-09-05 17:47

import utils.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_clientreview_home_client_is_feat_aa4573_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', validators=[utils.upload_validators.validate_image_10mb]),
        ),
    ]
