# Generated by Django 5.2.7 on 2026-01-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='id',
        ),
        migrations.AlterField(
            model_name='solution',
            name='slug',
            field=models.SlugField(help_text='Used in URLs and for identification', primary_key=True, serialize=False, unique=True),
        ),
    ]
