# Generated by Django 5.2.7 on 2026-01-29 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_solution_id_alter_solution_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demobooking',
            name='id',
        ),
        migrations.AlterField(
            model_name='demobooking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
