# Generated by Django 5.2.7 on 2026-01-29 08:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_demobooking_id_alter_demobooking_booking_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('iot', 'IoT'), ('ai', 'AI & ML'), ('scratch', 'Scratch for Kids'), ('web', 'Web Development'), ('mobile', 'Mobile Development'), ('data', 'Data Science'), ('security', 'Security')], max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], max_length=50)),
                ('badge', models.CharField(blank=True, choices=[('popular', 'Most Popular'), ('new', 'New'), ('advanced', 'Advanced'), ('kids', 'For Kids'), ('', 'No Badge')], max_length=50)),
                ('icon_class', models.CharField(choices=[('fab fa-python', 'Python'), ('fab fa-js-square', 'JavaScript'), ('fas fa-microchip', 'Microchip/IoT'), ('fas fa-robot', 'Robot/AI'), ('fas fa-server', 'Server'), ('fas fa-chart-line', 'Chart/Data'), ('fas fa-shield-alt', 'Shield/Security'), ('fas fa-gamepad', 'Gamepad/Kids'), ('fab fa-node-js', 'Node.js'), ('fas fa-laptop-code', 'Laptop Code'), ('fas fa-database', 'Database'), ('fas fa-cloud', 'Cloud')], max_length=50)),
                ('color', models.CharField(default='#3776AB', help_text='Hex color code', max_length=7)),
                ('short_description', models.CharField(max_length=200)),
                ('detailed_description', models.TextField()),
                ('duration', models.CharField(help_text='e.g., 12 Weeks', max_length=50)),
                ('lessons', models.CharField(help_text='e.g., 48 Lessons', max_length=50)),
                ('students_enrolled', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('instructor_name', models.CharField(max_length=100)),
                ('instructor_bio', models.TextField()),
                ('instructor_title', models.CharField(blank=True, help_text='e.g., Senior AI Engineer', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, help_text="JSON format: {'Mode': 'Online', 'Schedule': 'Mon & Wed'}")),
                ('curriculum', models.JSONField(blank=True, default=list, help_text='JSON array of modules with lessons')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseStat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_courses', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('satisfaction_rate', models.DecimalField(decimal_places=1, default=98.0, max_digits=4)),
                ('total_instructors', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Statistic',
                'verbose_name_plural': 'Course Statistics',
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-1 years)'), ('intermediate', 'Intermediate (1-3 years)'), ('advanced', 'Advanced (3+ years)')], max_length=50)),
                ('learning_goals', models.TextField(blank=True)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Home.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('email', 'course')},
            },
        ),
    ]
