"""
Django settings for BlackCodeLabs project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Overridable via a SECRET_KEY environment variable / .env entry — set a real
# random production value before going live (this fallback is dev-only).
SECRET_KEY = config('SECRET_KEY', default='django-insecure-mwn&bi$bd60hc5xg#vs_l@qgxy^6^l=)*%g!$=hcj89cm*4an1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["https://blackcodelab.com", "blackcodelab.com", "www.blackcodelab.com", "http://www.blackcodelab.com", "http://blackcodelab.com", "https://www.blackcodelab.com", "127.0.0.1", '10.5.5.208', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'Home.apps.HomeConfig',
    'Users',
    'Pitchs.apps.PitchsConfig',

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'Blogs',
    'Affiliate',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GCI'),
            'secret': config('GCS'),
            'key': ''
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'BlackCodeLabs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR , 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Home.context_processors.site_meta',
            ],
        },
    },
]

WSGI_APPLICATION = 'BlackCodeLabs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Keep DB connections open between requests instead of reconnecting
        # every time (huge win once you move to Postgres/MySQL; harmless
        # no-op on SQLite today).
        'CONN_MAX_AGE': 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'Home' / 'static',
]

# WhiteNoise: serve static files with hashed, cache-busted filenames, gzip +
# brotli pre-compression, and far-future Cache-Control headers. This is one
# of the single biggest wins for perceived load speed — repeat visits (and
# every asset after the first) get served straight from the browser cache.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 365  # 1 year — safe because filenames are hashed

MEDIA_URL = '/media/'
import os
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ---------------------------------------------------------------------------
# CACHING
# Uses a fast on-disk cache by default (works out of the box, survives across
# gunicorn/uwsgi worker processes — unlike LocMemCache). Set REDIS_URL in
# your environment to switch to Redis with zero code changes if you add one
# later (pip install django-redis).
# ---------------------------------------------------------------------------
REDIS_URL = config('REDIS_URL', default='')
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
            "TIMEOUT": 300,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
            "LOCATION": str(BASE_DIR / "django_cache"),
            "TIMEOUT": 300,
            "OPTIONS": {"MAX_ENTRIES": 1000},
        }
    }
CACHE_MIDDLEWARE_SECONDS = 300

# LOGGING CONFIGURATION
LOGS_DIR = BASE_DIR / 'logs'
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        # Dedicated rotating log file for the Telegram contact-form
        # notifier. Keep this separate from the general console log so you
        # can tail one file (logs/telegram.log) to see exactly whether a
        # message reached Telegram, or why it failed, without digging
        # through unrelated Django/request noise.
        'telegram_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'telegram.log'),
            'maxBytes': 1024 * 1024 * 2,  # 2 MB per file
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'Home': {  # Your app name
            'handlers': ['console'],
            'level': 'DEBUG',  # Set to DEBUG for more details
            'propagate': False,
        },
        'telegram': {
            'handlers': ['console', 'telegram_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

#timezone
TIME_ZONE = 'Africa/Nairobi'
USE_TZ = True

from decouple import config


# EMAIL CONFIGURATION FOR TESTING PURPOSES
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development - emails print to console
DEFAULT_FROM_EMAIL = 'noreply@blackcodelabs.com'
CONTACT_NOTIFICATION_EMAIL = 'sales@blackcodelabs.com'


CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'https://blackcodelabs.com', 'https://www.blackcodelabs.com']

# ---------------------------------------------------------------------------
# TELEGRAM NOTIFICATIONS
# Since there's no monitored email inbox, every contact-form submission is
# pushed straight to a Telegram chat so it can be seen immediately.
#
# Setup:
#   1. Message @BotFather on Telegram -> /newbot -> copy the bot token.
#   2. Message your new bot once (anything), then visit:
#        https://api.telegram.org/bot<TOKEN>/getUpdates
#      and copy the "chat":{"id": ...} value -> that's your TELEGRAM_CHAT_ID.
#   3. Put both values in your .env file (never commit real values):
#        TELEGRAM_BOT_TOKEN=123456:ABC-your-real-token
#        TELEGRAM_CHAT_ID=123456789
# If either is left blank, notifications are silently skipped (and logged)
# instead of breaking the contact form.
# ---------------------------------------------------------------------------
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_CHAT_ID = config('TELEGRAM_CHAT_ID', default='')

# ---------------------------------------------------------------------------
# SEO / SITE IDENTITY
# NOTE: ALLOWED_HOSTS above lists "blackcodelab.com" (no "s") in a few entries
# while emails/CSRF use "blackcodelabs.com". Confirm the real domain and make
# ALLOWED_HOSTS consistent before going live — canonical URLs, the sitemap and
# structured data below all use SITE_DOMAIN.
SITE_DOMAIN = config('SITE_DOMAIN', default='blackcodelabs.com')
SITE_URL = config('SITE_URL', default=f'https://{SITE_DOMAIN}')
SITE_NAME = 'BlackCodeLabs'

# Paste the verification codes/meta tags Google Search Console and Bing
# Webmaster Tools give you when you add the property — they render
# automatically in the <head> once set.
GOOGLE_SITE_VERIFICATION = config('GOOGLE_SITE_VERIFICATION', default='')
BING_SITE_VERIFICATION = config('BING_SITE_VERIFICATION', default='')

# Social links shown as icons in the footer. Leave any of these blank in your
# environment to hide that icon — set real URLs before launch.
# Number (with country code, no + or spaces) the floating WhatsApp button
# opens a chat with.
WHATSAPP_NUMBER = config('WHATSAPP_NUMBER', default='254731209601')

# Social links shown as icons in the footer. Leave any of these blank in your
# environment to hide that icon — set real URLs before launch.
SOCIAL_TWITTER = config('SOCIAL_TWITTER', default='https://twitter.com/blackcodelabs')
SOCIAL_LINKEDIN = config('SOCIAL_LINKEDIN', default='https://linkedin.com/company/blackcodelabs')
SOCIAL_GITHUB = config('SOCIAL_GITHUB', default='https://github.com/blackcodelabs')
SOCIAL_INSTAGRAM = config('SOCIAL_INSTAGRAM', default='')

# For production, uncomment and configure the following:
# EMAIL_BACKEND = config('EMAIL_BACKEND')
# EMAIL_HOST = config('EMAIL_HOST')
# EMAIL_PORT = int(config('EMAIL_PORT'))  # Default to 587 if not set
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')